import test from 'node:test';
import assert from 'node:assert/strict';
import {encryptBackup,decryptBackup,inspectEnvelope} from '../src/crypto.mjs';
import {chunks,vectors,rank,citations,classification,retentionPlan} from '../src/intelligence.mjs';
test('encrypted backup round trip, wrong password and tamper',async()=>{const password='synthetic-long-password',plain={text:'合成测试稿件'};const envelope=await encryptBackup(plain,password);assert(!JSON.stringify(envelope).includes(plain.text));assert.deepEqual(await decryptBackup(envelope,password),plain);await assert.rejects(()=>decryptBackup(envelope,'another-wrong-password'));await assert.rejects(()=>decryptBackup({...envelope,ciphertext:envelope.ciphertext.slice(0,-4)+'AAAA'},password));assert.throws(()=>inspectEnvelope({...envelope,iterations:1}));await assert.rejects(()=>encryptBackup(plain,'short'));});
test('chunk index isolates works and revisions and ignores deleted content',()=>{const d={id:'a',workId:'w',revision:2,title:'资料',kind:'material',content:'字'.repeat(2100)};const c=chunks([d,{...d,id:'b',deletedAt:'date'},{...d,id:'c',workId:'other'}],'w');assert.equal(c.length,3);assert.equal(c[1].start,900);assert.equal(c[2].text.length,300);assert.deepEqual(rank([{id:c[0].id,vector:[1,0]},{id:'a:1:0',vector:[1,0]}],c,[1,0]).map(x=>x.id),[c[0].id]);});
test('embedding response rejects malformed, missing and mismatched dimensions',()=>{assert.deepEqual(vectors({data:[{index:1,embedding:[0,1]},{index:0,embedding:[1,0]}]},2),[[1,0],[0,1]]);for(const data of [[{index:0,embedding:[0,0]}],[{index:2,embedding:[1,0]}],[{index:0,embedding:[NaN]}]])assert.throws(()=>vectors({data},1));assert.throws(()=>rank([{id:'a',vector:[1]}],[{id:'a'}],[1,0]));});
test('citation and category validation rejects invented identifiers and categories',()=>{assert.deepEqual(citations('有证据 [S1]',[{id:'a'}]),[{id:'a'}]);assert.throws(()=>citations('无出处',[]));assert.throws(()=>citations('[S2]',[{}]));assert.throws(()=>classification('{"category":"constructor","reason":"x"}'));assert.equal(classification('{"category":"world","reason":"设定"}').category,'world');});
test('retention preserves newest, first and restore nodes',()=>{const rows=Array.from({length:50},(_,i)=>({id:String(i),documentId:'a',revision:i+1,reason:i===5?'restore':'edit'}));const plan=retentionPlan(rows,5);assert.equal(plan.length,43);assert(!plan.some(x=>['0','5','49','45'].includes(x.id)));assert.throws(()=>retentionPlan(rows,0));});
