import {makeBlueprint} from '../src/blueprint.mjs?v=0.3.1';
import {importFile} from '../src/imports.mjs?v=0.3.1';
import {Repository} from '../src/storage.mjs?v=0.3.1';
import {searchDocuments,categorySuggestion,verifyBackup,digest,STORES,uid} from '../src/domain.mjs?v=0.3.1';
const results=document.getElementById('results'),summary=document.getElementById('summary');
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
document.getElementById('run').onclick=async()=>{
  document.getElementById('run').disabled=true;results.innerHTML='';let passed=0,failed=0;
  const test=async(name,fn)=>{const item=document.createElement('li');try{await fn();passed++;item.textContent='通过 · '+name;item.className='success';}catch(err){failed++;item.textContent='失败 · '+name+'：'+err.message;item.className='danger';}results.append(item);summary.textContent=`${passed} 通过 / ${failed} 失败`;};
  const name='novel-test-'+crypto.randomUUID();let repo=await new Repository(name).open();const other=await new Repository(name+'-restore').open();
  let work,chapter,material;
  try{
    await test('创建作品、章节与大纲',async()=>{const result=await repo.createWork('验收作品');work=result.work;chapter=result.chapter;assert((await repo.list('documents')).length===2,'初始结构错误');});
    await test('保存后关闭并重新打开仍可读取',async()=>{chapter=await repo.saveDocument(chapter.id,chapter.revision,{content:'林舟带着怀表走向灯塔。'});repo.close();repo=await new Repository(name).open();assert((await repo.get('documents',chapter.id)).content===chapter.content,'保存丢失');});
    await test('旧版本并发写入被拒绝，原文不覆盖',async()=>{let caught=false;try{await repo.saveDocument(chapter.id,1,{content:'应被拒绝'});}catch(err){caught=err.name==='ConflictError';}assert(caught,'没有检测冲突');assert((await repo.get('documents',chapter.id)).content===chapter.content,'原文被覆盖');});
    await test('恢复历史产生新版本，后续版本仍存在',async()=>{const first=(await repo.list('revisions')).find(r=>r.documentId===chapter.id&&r.revision===1);chapter=await repo.restoreRevision(chapter.id,chapter.revision,first.id);assert(chapter.revision===3&&chapter.content==='','恢复错误');assert((await repo.list('revisions')).filter(r=>r.documentId===chapter.id).length===3,'历史被破坏');});
    await test('移入回收站并找回',async()=>{chapter=await repo.saveDocument(chapter.id,chapter.revision,{deletedAt:new Date().toISOString()});assert(!!(await repo.get('documents',chapter.id)).deletedAt,'删除未保存');chapter=await repo.saveDocument(chapter.id,chapter.revision,{deletedAt:null});assert(!chapter.deletedAt,'未找回');});
    await test('任务完成状态保存且拒绝过期写入',async()=>{let task=await repo.createTask(work.id,'核对人物');task=await repo.toggleTask(task.id,1,true);assert(task.done,'未完成');let caught=false;try{await repo.toggleTask(task.id,1,false);}catch{caught=true;}assert(caught,'过期任务被覆盖');});
    await test('资料关联稳定，重复关联不重复创建',async()=>{material=await repo.addDocument(work.id,'material','人物设定','林舟的父亲留下了一块怀表。');await repo.link(work.id,material.id,chapter.id);await repo.link(work.id,material.id,chapter.id);assert((await repo.list('relations')).length===1,'重复关联');material=await repo.saveDocument(material.id,material.revision,{title:'新的资料名称'});assert((await repo.list('relations'))[0].fromId===material.id,'改名破坏关联');});
    await test('不允许跨作品关联',async()=>{const second=await repo.createWork('另一本');let caught=false;try{await repo.link(work.id,material.id,second.chapter.id);}catch{caught=true;}assert(caught,'跨作品关联被接受');});
    await test('中文短词查找与作品隔离',async()=>{const all=await repo.list('documents');const found=searchDocuments(all,work.id,'林舟');assert(found.length===1&&found[0].document.id===material.id,'中文检索错误');assert(searchDocuments(all,'不存在的作品','林舟').length===0,'检索跨作品');});
    await test('本地整理规则明确建议理由',async()=>{const suggestion=categorySuggestion(material);assert(suggestion.category==='character'&&suggestion.reason,'规则建议错误');});
    await test('资料可直接归入情节分类，非法分类不写入',async()=>{const doc=await repo.addDocument(work.id,'material','','主角遇到阻碍。',null,'plot');assert(doc.title==='未命名资料'&&doc.category==='plot','选填标题或分类未保存');const count=(await repo.list('documents')).length;let rejected=false;try{await repo.addDocument(work.id,'material','错误类别','内容',null,'unknown');}catch{rejected=true;}assert(rejected&&(await repo.list('documents')).length===count,'非法分类写入了资料');rejected=false;try{await repo.saveDocument(doc.id,doc.revision,{category:'unknown'});}catch{rejected=true;}assert(rejected&&(await repo.get('documents',doc.id)).category==='plot','非法改分类覆盖了原分类');});
    await test('事务写入中断会整体回滚',async()=>{const before=await repo.get('documents',chapter.id);let rejected=false;try{await repo.transact(['documents','revisions'],(store,done,abort)=>{store('documents').put({...before,content:'不可留下的半次写入'});abort(new Error('注入事务失败'));});}catch{rejected=true;}assert(rejected,'事务未拒绝');assert((await repo.get('documents',chapter.id)).content===before.content,'半次写入未回滚');});
    await test('TXT 导入保留原始来源并拦截重复',async()=>{const file=new File(['参考资料：港口的历史。'],'港口.txt',{type:'text/plain'});const doc=await importFile(repo,work.id,file);assert(doc.category==='inbox'&&!!doc.sourceId,'没有收进待整理');const source=await repo.get('sources',doc.sourceId);assert(source.originalName==='港口.txt'&&!!source.sha256&&!!source.base64,'来源未保留');let caught=false;try{await importFile(repo,work.id,file);}catch(err){caught=err.name==='DuplicateError';}assert(caught,'重复未提示');});
    await test('空文本、非法编码、不支持格式拒绝导入',async()=>{const files=[new File([''],'空.txt'),new File([new Uint8Array([255,254,253])],'编码.txt'),new File(['正文'],'稿件.pdf')];const count=(await repo.list('documents')).length;for(const file of files){let caught=false;try{await importFile(repo,work.id,file);}catch{caught=true;}assert(caught,'非法文件被导入');}assert((await repo.list('documents')).length===count,'失败污染文档');});
    await test('任务关联章节，改名后编号和引用保持',async()=>{const task=await repo.createTask(work.id,'补全开场',chapter.id);chapter=await repo.saveDocument(chapter.id,chapter.revision,{title:'新开场'});assert((await repo.get('tasks',task.id)).chapterId===chapter.id,'改名破坏任务关联');});
    await test('任务拒绝跨作品、资料和已删除章节',async()=>{const second=(await repo.list('documents')).find(d=>d.workId!==work.id&&d.kind==='chapter');const removed=await repo.addDocument(work.id,'chapter','暂时移除');await repo.saveDocument(removed.id,removed.revision,{deletedAt:new Date().toISOString()});const before=(await repo.list('tasks')).length;for(const id of [second.id,material.id,removed.id]){let caught=false;try{await repo.createTask(work.id,'不应创建',id);}catch{caught=true;}assert(caught,'非法章节关联被接受');}assert((await repo.list('tasks')).length===before,'失败创建残留任务');});
    await test('任务调整关联检查版本，取消不修改章节',async()=>{let task=await repo.createTask(work.id,'调整章节');task=await repo.setTaskChapter(task.id,task.revision,chapter.id);let caught=false;try{await repo.setTaskChapter(task.id,1,null);}catch{caught=true;}assert(caught,'旧版本覆盖关联');const before=await repo.get('documents',chapter.id);task=await repo.setTaskChapter(task.id,task.revision,null);assert(task.chapterId===null,'取消关联失败');assert((await repo.get('documents',chapter.id)).revision===before.revision,'关联操作修改了章节');});
    await test('校验拒绝任务版本、错误关联类型和伪类别',async()=>{for(const mutate of [b=>b.tasks[0].revision=0,b=>b.revisions[0].category='不存在的分类',b=>b.tasks[0].chapterId=material.id,b=>b.relations[0].toId=material.id,b=>b.documents[0].kind='constructor',b=>b.documents[0].category='toString',b=>b.revisions.push({...b.revisions[0],id:uid()})]){const b=await repo.exportBackup();mutate(b);const payload=Object.fromEntries(STORES.map(k=>[k,b[k]]));b.checksum=await digest(JSON.stringify(payload));let caught=false;try{await other.restoreBackup(b);}catch{caught=true;}assert(caught,'结构错误未被拒绝');}assert((await other.list('works')).length===0,'非法恢复写入数据');});
    await test('完整备份在空库恢复，正文、版本、关联与任务一致',async()=>{const backup=await repo.exportBackup();await verifyBackup(backup);const restored=await other.restoreBackup(backup),actual=await other.all();for(const key of ['works','documents','revisions','relations','tasks'])assert(actual[key].length===backup[key].length,key+' 数量不一致');assert(restored.documents.some(d=>d.content===material.content),'正文不一致');assert(restored.relations.every(r=>actual.documents.some(d=>d.id===r.fromId)),'关联未重映射');assert(actual.documents.every(d=>!backup.documents.some(old=>old.id===d.id)),'编号未变化');const linked=actual.tasks.find(t=>t.text==='补全开场');assert(linked&&actual.documents.some(d=>d.id===linked.chapterId&&d.title==='新开场'),'任务章节未重映射');});
    await test('损坏与未知版本备份拒绝，资料库不变',async()=>{const before=(await other.list('documents')).length;const bad=await repo.exportBackup();bad.documents[0].content='篡改';let caught=false;try{await other.restoreBackup(bad);}catch{caught=true;}assert(caught,'损坏未拦截');bad.schemaVersion=999;caught=false;try{await other.restoreBackup(bad);}catch{caught=true;}assert(caught,'未知版本未拦截');assert((await other.list('documents')).length===before,'非法恢复污染数据');});
    await test('写作空间原子创建大纲、章节、资料和任务',async()=>{const plan=makeBlueprint({intent:'我想写《开源验收》',scenario:'clues'});const result=await repo.createFromBlueprint(plan);assert(result.work.title==='开源验收','作品名错误');assert((await repo.list('documents')).filter(d=>d.workId===result.work.id).length===3,'交付内容不完整');assert(result.documents.find(d=>d.kind==='material').category==='clue','场景模板分类未保存');assert((await repo.list('tasks')).filter(t=>t.workId===result.work.id).every(t=>t.chapterId===result.chapter.id),'任务未绑定正文');});
    await test('稿件迁移保留粘贴原文且不污染其他作品',async()=>{const old=await repo.get('documents',chapter.id);const raw='  验收原文：林舟\n保持原来的换行。 ';const result=await repo.createFromBlueprint(makeBlueprint({route:'migrate',material:raw}));assert(result.documents.find(d=>d.kind==='material').content===raw,'原文被改写');assert((await repo.get('documents',chapter.id)).content===old.content,'旧作品被修改');});
    await test('无效写作结构在写入前拒绝',async()=>{const count=(await repo.list('works')).length;let caught=false;try{await repo.createFromBlueprint({title:'错误',documents:[{kind:'unsupported'}],tasks:[]});}catch{caught=true;}assert(caught&&(await repo.list('works')).length===count,'无效写作结构污染资料库');});
    await test('删除的资料不出现在搜索中',async()=>{material=await repo.saveDocument(material.id,material.revision,{deletedAt:new Date().toISOString()});assert(searchDocuments(await repo.list('documents'),work.id,'怀表').length===0,'删除资料仍出现');});
  }finally{repo.close();other.close();indexedDB.deleteDatabase(name);indexedDB.deleteDatabase(name+'-restore');document.getElementById('run').disabled=false;summary.textContent=`完成：${passed} 通过 / ${failed} 失败。测试库已关闭并请求清理。`;}
};
