import {digest,CATEGORIES} from './domain.mjs?v=0.4.0';
export function chunks(documents,workId){return documents.filter(d=>d.workId===workId&&!d.deletedAt&&d.content.trim()).flatMap(d=>{const out=[];for(let start=0;start<d.content.length;start+=900){out.push({id:d.id+':'+d.revision+':'+start,documentId:d.id,revision:d.revision,title:d.title,kind:d.kind,start,text:d.content.slice(start,start+1000)});if(start+1000>=d.content.length)break;}return out;});}
export async function fingerprint(config){return digest(JSON.stringify([config.base,config.embeddingModel]));}
export function validVector(v){return Array.isArray(v)&&v.length>0&&v.length<=8192&&v.every(x=>typeof x==='number'&&Number.isFinite(x))&&v.some(x=>x!==0);}
export function vectors(response,count){if(!Array.isArray(response?.data)||response.data.length!==count)throw Error('模型返回的向量数量不一致');const ordered=[...response.data].sort((a,b)=>a.index-b.index);if(ordered.some((x,i)=>x.index!==i||!validVector(x.embedding))||ordered.some(x=>x.embedding.length!==ordered[0].embedding.length))throw Error('模型返回的向量格式错误');return ordered.map(x=>x.embedding);}
export function cosine(a,b){if(!validVector(a)||!validVector(b)||a.length!==b.length)throw Error('索引模型或维度不一致，请重建索引');let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return dot/Math.sqrt(aa*bb);}
export function rank(index,current,query,limit=5){const active=new Map(current.map(c=>[c.id,c]));return index.filter(x=>active.has(x.id)).map(x=>({...active.get(x.id),score:cosine(x.vector,query)})).sort((a,b)=>b.score-a.score).slice(0,limit);}
export function citations(text,sources){const ids=[...text.matchAll(/\[S(\d+)\]/g)].map(m=>Number(m[1]));if(!ids.length||ids.some(n=>n<1||n>sources.length))throw Error('回答缺少有效出处，已拦截。请缩小问题范围重试。');return [...new Set(ids)].map(n=>sources[n-1]);}
export function classification(text){let value;try{value=JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g,''));}catch{throw Error('分类结果不是有效 JSON，未修改资料');}if(!Object.hasOwn(CATEGORIES,value.category)||typeof value.reason!=='string'||value.reason.length>500)throw Error('分类结果不符合要求，未修改资料');return value;}
export function retentionPlan(revisions,keep=30){if(!Number.isInteger(keep)||keep<5||keep>200)throw Error('每份内容须保留 5–200 个最近版本');const groups=new Map();for(const r of revisions){if(!groups.has(r.documentId))groups.set(r.documentId,[]);groups.get(r.documentId).push(r);}const remove=[];for(const rows of groups.values()){rows.sort((a,b)=>b.revision-a.revision);const first=rows.at(-1)?.id;remove.push(...rows.slice(keep).filter(r=>r.id!==first&&!['restore','setup','create'].includes(r.reason)));}return remove;}
export function chatText(response){const text=response?.choices?.[0]?.message?.content;if(typeof text!=='string'||text.length>24000)throw Error('模型未返回可用文本');return text;}
