import {escapeHTML as e,CATEGORIES,CATEGORY_HINTS,KINDS,searchDocuments,categorySuggestion} from './domain.mjs?v=0.4.0';
import {importFile,LIMITS} from './imports.mjs?v=0.4.0';
import {bucketCount,bucketLength} from './analytics.mjs?v=0.4.1';
const $=id=>document.getElementById(id);
export function libraryUI(ctx){
  const {repo,state,docs,currentWork,flush,refresh,render,navigate,modal,closeModal,guard,notify,track,getDoc,backupModal,download}=ctx;
  let undo=null;
  function renderLibrary(){const items=docs().filter(d=>d.kind==='material'&&(state.filter==='all'||d.category===state.filter));const total=docs().filter(d=>d.kind==='material');$('stage').innerHTML=`<div class="stage-heading"><div><p class="eyebrow">${e(currentWork().title)} / 资料箱</p><h1>先收好，不用一次理清。</h1><p class="muted small">人物、设定和一闪而过的灵感，都放在这里。</p></div><div class="actions"><button id="library-search" class="secondary">找资料</button><button id="library-import" class="primary">放入资料</button></div></div><details class="category-help"><summary>不知道放哪一类？看分类例子</summary><p class="small muted">按以后最想怎样找回它来选；拿不准就放“待整理”，不会丢。</p><ul>${Object.entries(CATEGORIES).filter(([id])=>id!=="inbox").map(([id,label])=>`<li><strong>${label}</strong>：${e(CATEGORY_HINTS[id])}</li>`).join("")}</ul></details><div class="filters" aria-label="资料分类"><button data-category="all" class="${state.filter==='all'?'active':''}">全部 ${total.length}</button>${Object.entries(CATEGORIES).map(([id,label])=>`<button data-category="${id}" class="${state.filter===id?'active':''}">${label}${id==='inbox'?' '+total.filter(d=>d.category==='inbox').length:''}</button>`).join('')}</div>${items.length?`<div class="library-grid">${items.map(d=>`<button data-material="${d.id}" class="material-card"><span class="badge">${CATEGORIES[d.category]}</span><h3>${e(d.title)}</h3><p>${e(d.content)}</p><div class="card-footer"><span class="small muted">${state.relations.filter(r=>r.fromId===d.id&&docs().some(x=>x.id===r.toId)).length} 处章节关联</span></div></button>`).join('')}</div>`:`<div class="empty"><h2>${total.length?'这一类还没有资料':'给散落的想法一个位置'}</h2><p>粘贴一段文字，或放入 TXT / Markdown 文件。可以先不分类。</p><button id="empty-import" class="primary">放入第一份资料</button></div>`}`;
    $('library-import').onclick=guard(showImport);$('library-search').onclick=guard(()=>navigate('search'));if($('empty-import'))$('empty-import').onclick=guard(showImport);
    document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.category;renderLibrary();});document.querySelectorAll('[data-material]').forEach(b=>b.onclick=guard(()=>navigate('write',b.dataset.material)));
  }
  async function showImport(){if(!await flush())return;modal('放入资料',`<p class="small muted">只需粘贴内容就能保存；标题和分类都可稍后补。也可直接导入文件。</p><form id="paste-form"><label for="material-content">粘贴内容 <span class="field-status">必填</span></label><textarea id="material-content" class="field area" required placeholder="可以是一段设定、一句灵感，或已有的稿件……"></textarea><label for="material-title">资料名称 <span class="field-status">选填</span></label><input id="material-title" class="field" maxlength="150" placeholder="留空会叫“未命名资料”"><details class="optional-fields"><summary>想顺手归类？<span class="field-status">选填</span></summary><label for="material-category-new">最可能在哪儿找它</label><select id="material-category-new" class="field">${Object.entries(CATEGORIES).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select><p class="small muted">不确定就保持“待整理”。一份资料只选一个主要位置，人物名、地点可稍后写进关键词。</p></details><button class="primary">保存这份资料</button></form><div class="setting-row"><div><label for="material-files">或者导入 TXT / Markdown 文件 <span class="field-status">文件方式必选</span></label><p class="small muted">无需填写上方字段。导入后先放“待整理”；每次最多 20 个，单个 2 MiB，整批 20 MiB。</p><input id="material-files" type="file" accept=".txt,.md,text/plain,text/markdown" multiple></div></div><ul id="import-results" class="file-results" aria-live="polite"></ul><button id="import-finish" class="secondary full" hidden>去资料箱看看</button>`);
    $('paste-form').onsubmit=guard(async ev=>{ev.preventDefault();const content=$('material-content').value;if(!content.trim())return;if(new TextEncoder().encode(content).length>LIMITS.file)throw new Error('文字超过 2 MiB，请分成几份放入。');const category=$('material-category-new').value;await repo.addDocument(state.workId,'material',$('material-title').value,content,null,category);await track('paste_saved',{entry_mode:'paste'},{source:'library',input_length_bucket:bucketLength(content.length)});await track('input_completed',{entry_mode:'paste'},{source:'library',input_length_bucket:bucketLength(content.length)});await track('material_captured',{}, {source:'library'});await refresh();closeModal();state.page='library';state.filter=category;render();notify(category==='inbox'?'已收进待整理，可以慢慢分类。':'资料已保存到“'+CATEGORIES[category]+'”，以后可以调整。');});
    $('material-files').onchange=guard(async ev=>{const files=[...ev.target.files];if(files.length>LIMITS.count)throw new Error('一次最多放入 20 个文件。');if(files.reduce((n,f)=>n+f.size,0)>LIMITS.batch)throw new Error('整批文件超过 20 MiB。');const output=$('import-results');output.innerHTML='';ev.target.disabled=true;
      try{for(const file of files){const row=document.createElement('li');output.append(row);const format=file.name.toLowerCase().endsWith('.md')?'md':'txt';await track('import_started',{entry_mode:'file'},{source:'library',import_format:format});try{await importFile(repo,state.workId,file);row.textContent='文件已收进待整理';row.className='success';await track('import_succeeded',{entry_mode:'file'},{source:'library',import_format:format});await track('input_completed',{entry_mode:'file'},{source:'library',import_format:format});await track('material_captured',{}, {source:'library'});}catch(err){row.textContent='导入失败：'+err.message;row.className='danger';if(err.name==='DuplicateError'){const b=document.createElement('button');b.textContent='仍保留副本';b.className='secondary';b.onclick=guard(async()=>{b.disabled=true;try{await importFile(repo,state.workId,file,true);row.textContent='已保留副本';row.className='success';await track('import_succeeded',{entry_mode:'file'},{source:'library',import_format:format});await track('input_completed',{entry_mode:'file'},{source:'library',import_format:format});await track('material_captured',{}, {source:'library'});await refresh();}catch(error){b.disabled=false;throw error;}});row.append(document.createElement('br'),b);}}}await refresh();$('import-finish').hidden=false;}finally{ev.target.disabled=false;}
    });$('import-finish').onclick=()=>{closeModal();state.page='library';state.filter='inbox';render();};
  }
  function renderSearch(){const found=searchDocuments(state.documents,state.workId,state.query);$('stage').innerHTML=`<div class="stage-heading"><div><p class="eyebrow">${e(currentWork().title)} / 找资料</p><h1>记得一句，也能找回来。</h1><p class="muted small">只查这部作品的正文、大纲与资料。使用标题、人名或一段原文。</p></div><button id="search-back" class="quiet">返回写作</button></div><form id="search-form" class="search-form"><input id="query" class="field" aria-label="查找关键词" value="${e(state.query)}" placeholder="例如：怀表、林舟、灯塔……"><button class="primary">查找</button></form><div id="search-results">${!state.query?'<div class="empty">输入一个人名或片段，开始查找。</div>':found.length?`<p class="small muted">找到 ${found.length} 份内容</p>${found.map(r=>`<article class="result"><span class="badge">${KINDS[r.document.kind]}</span><h3>${e(r.document.title)}</h3><p>${e(r.snippet||'标题命中')}</p><button class="secondary" data-result="${r.document.id}" data-offset="${r.offset}">打开原文</button></article>`).join('')}`:'<div class="empty">没有在这部作品中找到，可以换个人名或一句原文试试。</div>'}</div><p class="small muted">这里使用本地文字查找；可在智能助手中选择是否连接自己的模型服务。</p>`;
    $('search-form').onsubmit=ev=>{ev.preventDefault();state.query=$('query').value.trim();track('search_started',{}, {source:'search'});renderSearch();};$('search-back').onclick=guard(()=>navigate('write'));
    document.querySelectorAll('[data-result]').forEach(b=>b.onclick=guard(async()=>{const id=b.dataset.result,foundCount=document.querySelectorAll('[data-result]').length;if(!await navigate('write',id))return;const d=getDoc();const q=state.query.split(/\s+/).find(t=>d.content.toLowerCase().includes(t.toLowerCase()));const at=q?d.content.toLowerCase().indexOf(q.toLowerCase()):0;$('editor').focus();$('editor').setSelectionRange(at,at+(q?.length||0));await track('search_result_opened',{}, {source:'search',result_count_bucket:bucketCount(foundCount)});notify(q?'已选中原文中的命中片段。':'标题命中，已打开原文。');}));
  }
  function renderSupport(doc){
    const activeDocs=docs(),chapters=activeDocs.filter(d=>d.kind==='chapter'),source=state.sources.find(s=>s.id===doc.sourceId);
    if(doc.kind==='material'){
      const suggestion=categorySuggestion(doc),links=state.relations.filter(r=>r.fromId===doc.id&&activeDocs.some(d=>d.id===r.toId));
      $('support').innerHTML=`<section class="support-card"><h3>整理这份资料</h3><p class="small muted">先找得到，再慢慢理清。分类、关键词和章节关联都可跳过。</p><label for="material-category">主要分类 <span class="field-status">选填</span></label><select id="material-category" class="field">${Object.entries(CATEGORIES).map(([id,label])=>`<option value="${id}" ${doc.category===id?'selected':''}>${label}</option>`).join('')}</select><p class="small muted">${e(CATEGORY_HINTS[doc.category])}</p><label for="material-tags">关键词 <span class="field-status">选填</span></label><input id="material-tags" class="field" value="${e(doc.tags.join('，'))}" placeholder="人名、地名，用逗号分开"><button id="save-tags" class="secondary full">保存关键词</button><p class="small muted" style="margin-top:14px">关键词会帮助写作时发现相关资料。</p>${doc.category==='inbox'&&suggestion.category!=='inbox'?`<div class="notice-inline"><p>本地规则建议：${CATEGORIES[suggestion.category]}</p><p class="small">${e(suggestion.reason)}，不是 AI 判断。</p><button id="accept-category" class="secondary full">采用分类建议</button></div>`:''}${undo?.id===doc.id&&undo.revision===doc.revision?'<button id="undo-category" class="quiet full">撤销刚才的分类建议</button>':''}</section><section class="support-card"><h3>用在哪一章</h3>${links.map(r=>`<div class="link-card"><button data-linked-chapter="${r.toId}">${e(activeDocs.find(d=>d.id===r.toId).title)}</button><button data-unlink="${r.id}" class="quiet">取消关联</button></div>`).join('')||'<p>先关联到一章，写作时就能随手找到。</p>'}<label for="link-chapter">关联章节 <span class="field-status">选填</span></label><select id="link-chapter" class="field">${chapters.map(c=>`<option value="${c.id}">${e(c.title)}</option>`).join('')}</select><button id="link-material" class="secondary full" ${!chapters.length?'disabled':''}>关联到这一章</button></section><section class="support-card"><h3>原始来源</h3><p>${source?e(source.originalName):'直接粘贴或在此创建'}</p>${source?'<button id="source-download" class="quiet">下载原始文件</button>':''}<p class="small">编辑后的内容与原始文件分别保存。</p></section>`;
      const patch=async(data,reason)=>{if(!await flush())return;const fresh=getDoc();const saved=await repo.saveDocument(fresh.id,fresh.revision,data,reason);await refresh();render();return saved;};
      $('material-category').onchange=guard(ev=>patch({category:ev.target.value},'classify'));
      $('save-tags').onclick=guard(()=>patch({tags:[...new Set($('material-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean))].slice(0,20)},'tags'));
      if($('accept-category'))$('accept-category').onclick=guard(async()=>{const old=doc.category;const saved=await patch({category:suggestion.category},'rule-suggestion');if(saved){undo={id:saved.id,revision:saved.revision,category:old};renderSupport(saved);notify('已采用本地规则建议，可以撤销。');}});
      if($('undo-category'))$('undo-category').onclick=guard(async()=>{if(getDoc().revision!==undo.revision)throw new Error('内容已变化，请手动调整分类。');const previous=undo.category;undo=null;await patch({category:previous},'undo-suggestion');});
      $('link-material').onclick=guard(async()=>{if(!await flush())return;await repo.link(state.workId,doc.id,$('link-chapter').value);await refresh();render();await track('material_linked',{}, {source:'library',result:'success'});notify('已关联，章节旁会显示这份资料。');});
      document.querySelectorAll('[data-unlink]').forEach(b=>b.onclick=guard(async()=>{await repo.unlink(b.dataset.unlink);await refresh();renderSupport(getDoc());}));
      document.querySelectorAll('[data-linked-chapter]').forEach(b=>b.onclick=guard(()=>navigate('write',b.dataset.linkedChapter)));
      if($('source-download'))$('source-download').onclick=()=>{const bytes=Uint8Array.from(atob(source.base64),c=>c.charCodeAt(0));download(source.originalName,bytes,source.mime);};
    }else{
      const related=state.relations.filter(r=>r.toId===doc.id).map(r=>activeDocs.find(d=>d.id===r.fromId)).filter(Boolean);
      const suggestions=activeDocs.filter(d=>d.kind==='material'&&!related.some(x=>x.id===d.id)).map(d=>({doc:d,word:d.tags.find(t=>t.length>=2&&doc.content.includes(t))})).filter(x=>x.word).slice(0,3);
      $('support').innerHTML=`<section class="support-card"><p class="eyebrow">写作时，随手看看</p><h3>相关资料</h3>${related.length?related.map(d=>`<div class="link-card"><span class="badge">${CATEGORIES[d.category]}</span><br><button data-reference="${d.id}">${e(d.title)}</button></div>`).join(''):'<p>还没有关联资料。先把人物设定或灵感放进资料箱。</p>'}<button id="support-library" class="quiet">打开资料箱 ↗</button></section>${suggestions.length?`<section class="support-card"><h3>也许用得上</h3><p class="small">根据相同关键词推荐</p>${suggestions.map(({doc:d,word})=>`<div class="link-card"><button data-reference="${d.id}">${e(d.title)}</button><p class="small">这份资料的关键词“${e(word)}”出现在当前正文中。</p></div>`).join('')}</section>`:''}<section class="support-card"><h3>文字已留在这里</h3><p>每次保存都有历史版本。建议定期把完整备份带走。</p><button id="support-backup" class="quiet">备份与恢复 ↗</button></section>`;
      $('support-library').onclick=guard(()=>navigate('library'));$('support-backup').onclick=guard(backupModal);
      document.querySelectorAll('[data-reference]').forEach(b=>b.onclick=guard(async()=>{if(!await flush())return;await refresh();const d=docs().find(x=>x.id===b.dataset.reference);if(!d)throw new Error('这份资料已被移除。');modal(d.title,`<p class="small muted">${CATEGORIES[d.category]} · 当前版本 ${d.revision}</p><div class="preview-text">${e(d.content)}</div><div class="card-footer"><button id="reference-edit" class="secondary">打开编辑</button><button id="reference-close" class="primary">回去继续写</button></div>`);$('reference-close').onclick=closeModal;$('reference-edit').onclick=guard(async()=>{closeModal();await navigate('write',d.id);});track('source_located',{kind:'material'});}));
    }
  }
  return {renderLibrary,renderSearch,renderSupport,showImport};
}
