import {setupUI} from './setup.mjs?v=0.4.0';
import {tasksUI} from './tasks.mjs?v=0.4.0';
import {backupUI} from './backup.mjs?v=0.4.0';
import {libraryUI} from './library.mjs?v=0.4.0';
import {VaultRepository as Repository} from './vault.mjs?v=0.4.0';
import {advancedUI} from './advanced.mjs?v=0.4.0';
import {liveUI} from './live.mjs?v=0.4.0';
import {escapeHTML as e, KINDS, now} from './domain.mjs?v=0.4.0';
import {track as recordEvent} from './analytics.mjs?v=0.4.0';
import {initFunnel} from './funnel.mjs?v=0.4.0';
const $=id=>document.getElementById(id);
const qa=new URLSearchParams(location.search).get('qa')==='1';
const repo=new Repository(qa?'novel-qa-ui-v1':'novel-author-v1');
const state={works:[],documents:[],tasks:[],relations:[],sources:[],workId:null,docId:null,page:'write',filter:'all',query:''};
let base=null,dirty=false,composing=false,timer=null,saving=null,noticeTimer=null,modalTrigger=null;
let funnelContext={route:null,entry_mode:null};
function setFunnelContext(context={}){funnelContext={...funnelContext,...context};}
async function track(name,context={},props={}){
  if(context.route||context.entry_mode)setFunnelContext(context);
  try{return await recordEvent(name,{...funnelContext,...context},props);}catch{return null;}
}
const funnelReady=initFunnel().catch(()=>null);
function notify(message){clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').hidden=false;noticeTimer=setTimeout(()=>$('notice').hidden=true,4000);}
function status(message,bad=false){$('save-status').textContent=(qa?'测试区 · ':'')+message;$('save-status').style.color=bad?'var(--danger)':'var(--muted)';}
function download(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCurrent(){const title=$('doc-title')?.value||base?.title||'未保存内容';const text=$('editor')?.value??base?.content??'';download(title+'.txt',text);}
function modal(title,html){modalTrigger=document.activeElement;$('modal-title').textContent=title;$('modal-body').innerHTML=html;$('modal-error').textContent='';if(!$('modal').open)$('modal').showModal();}
function closeModal(){$('modal').close();modalTrigger?.focus?.();}
function modalError(err){$('modal-error').textContent=err.message||String(err);}
function guard(fn){return async (...args)=>{try{await fn(...args);}catch(err){console.error("操作失败",err.name||"Error");if($('modal').open)modalError(err);else notify(err.message||'操作失败，请重试。');}};}
async function refresh(){[state.works,state.documents,state.tasks,state.relations,state.sources]=await Promise.all(['works','documents','tasks','relations','sources'].map(k=>repo.list(k)));state.works=state.works.filter(w=>!w.deletedAt);if(!state.works.some(w=>w.id===state.workId))state.workId=state.works[0]?.id||null;}
const docs=()=>state.documents.filter(d=>d.workId===state.workId&&!d.deletedAt).sort((a,b)=>a.order-b.order);
const currentWork=()=>state.works.find(w=>w.id===state.workId);
function chooseDoc(){if(!docs().some(d=>d.id===state.docId))state.docId=docs().find(d=>d.kind==='chapter')?.id||docs()[0]?.id||null;}
async function remember(){await repo.setMeta('last-position',{workId:state.workId,docId:state.docId});}
async function navigate(page,docId){if(!await flush())return;state.page=page;if(docId)state.docId=docId;await refresh();chooseDoc();await remember();render();}
function render(){if(!state.workId){welcome();return;}status('本机资料已载入');chooseDoc();const selected=state.documents.find(d=>d.id===state.docId);$('app').innerHTML=`<div class="workspace"><aside class="sidebar" id="sidebar"><div class="work-select"><select id="work-select" aria-label="切换作品">${state.works.map(w=>`<option value="${w.id}" ${w.id===state.workId?'selected':''}>${e(w.title)}</option>`).join('')}</select><button id="new-work" aria-label="新建作品">＋</button></div><nav class="main-nav" aria-label="主导航"><button data-page="write" class="${state.page==='write'?'active':''}">写作</button><button data-page="library" class="${state.page==='library'?'active':''}">资料</button><button data-page="tasks" class="${state.page==='tasks'?'active':''}">任务</button></nav><button id="mobile-directory" class="secondary mobile-only" aria-expanded="false">展开章节目录</button><div class="outline-container"><div class="section-caption"><p>故事目录</p><button id="new-chapter" class="quiet" aria-label="新建章节">＋</button></div><div class="chapter-list">${docs().filter(d=>d.kind!=='material').map(d=>`<button data-doc="${d.id}" class="chapter-item ${d.id===state.docId&&state.page==='write'?'active':''}">${d.kind==='outline'?'◇ ':''}${e(d.title)}</button>`).join('')}</div></div><div class="sidebar-footer"><p>本机稿件已加密保存。<br>定期备份，离开时锁定。</p><button id="trash-open" class="quiet">回收站</button></div></aside><main class="stage"><div id="stage"></div></main></div>`;
  $('work-select').onchange=guard(async ev=>{const next=ev.target.value;if(!await flush()){ev.target.value=state.workId;return;}state.workId=next;state.docId=null;state.page='write';chooseDoc();await remember();render();});
  $('new-work').onclick=guard(newWorkModal);$('new-chapter').onclick=guard(()=>addChapter());
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=guard(()=>navigate(b.dataset.page)));
  document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=guard(()=>navigate('write',b.dataset.doc)));
  $('mobile-directory').onclick=()=>{const expanded=$('sidebar').classList.toggle('expanded');$('mobile-directory').setAttribute('aria-expanded',expanded);$('mobile-directory').textContent=expanded?'收起章节目录':'展开章节目录';};
  $('trash-open').onclick=guard(trashModal);
  if(state.page==='tasks')renderTasks();else if(state.page==='library')renderLibrary();else if(state.page==='search')renderSearch();else renderEditor(selected);
}
function welcome(){base=null;status('本地写作空间');setup.open();}
async function newWorkModal(){return setup.open();}
async function blankWorkModal(){if(!await flush())return;modal('开始一个新故事',`<form id="new-work-form"><label for="work-title">作品名称 <span class="field-status">选填</span></label><input class="field" id="work-title" maxlength="80" placeholder="现在不确定也没关系"><p class="muted small">留空会先叫“未命名作品”，以后可以修改。</p><button class="primary">进入写作</button></form>`);$('new-work-form').onsubmit=guard(async ev=>{ev.preventDefault();const {work,chapter}=await repo.createWork($('work-title').value);state.workId=work.id;state.docId=chapter.id;state.page='write';await refresh();await remember();closeModal();render();$('editor').focus();await track('workspace_created',{route:funnelContext.route||'new_story'});await track('first_artifact_ready',{route:funnelContext.route||'new_story'});});}
async function addChapter(){if(!await flush())return;modal('新建章节',`<form id="chapter-form"><label for="chapter-title">章节名称 <span class="field-status">选填</span></label><input id="chapter-title" class="field" maxlength="100" placeholder="例如：第二章 · 灯塔"><button class="primary">开始这一章</button></form>`);$('chapter-form').onsubmit=guard(async ev=>{ev.preventDefault();const d=await repo.addDocument(state.workId,'chapter',$('chapter-title').value);state.docId=d.id;state.page='write';await refresh();await remember();closeModal();render();$('editor').focus();});}
function editorValues(){return {title:$('doc-title')?.value||base?.title||'',content:$('editor')?.value??base?.content??''};}
function renderEditor(doc){base=doc?structuredClone(doc):null;dirty=false;if(!doc){$('stage').innerHTML='<div class="empty"><h2>还没有章节</h2><p>用左侧的 ＋ 新建一章，或者去回收站找回。</p><button id="empty-chapter" class="primary">新建章节</button><button id="empty-trash" class="quiet">打开回收站</button></div>';$('empty-chapter').onclick=guard(addChapter);$('empty-trash').onclick=guard(trashModal);return;}
  status('已保存到此浏览器');$('stage').innerHTML=`<div class="stage-heading"><div><p class="eyebrow">${e(currentWork().title)} / ${KINDS[doc.kind]}</p><h1>${doc.kind==='material'?'每个想法，都有落脚处。':doc.kind==='outline'?'把故事的脉络，理清一点。':'故事，从这里继续。'}</h1></div><div class="actions"><button id="search-open" class="secondary">找资料</button>${doc.kind==='chapter'?'<button id="live-open" class="secondary">协作编辑</button>':''}<button id="history-open" class="quiet">历史版本</button><button id="doc-more" class="quiet">更多</button></div></div><div id="editor-warning" class="notice-inline" role="alert"></div><div class="editor-layout"><article class="manuscript"><label for="doc-title" class="eyebrow">${KINDS[doc.kind]}名称 <span class="field-status">选填</span></label><input id="doc-title" class="doc-title" maxlength="150" value="${e(doc.title)}"><label for="editor" class="eyebrow">${doc.kind==='material'?'资料原文':'正文'} <span class="field-status">选填 · 可先留空</span></label><textarea id="editor" placeholder="先写下一句话。思路可以慢慢展开……" spellcheck="false">${e(doc.content)}</textarea><div class="editor-footer"><span id="word-count">${doc.content.length} 字符</span><button id="save-now" class="quiet">立即保存</button></div></article><aside id="support" class="support"></aside></div>`;
  const onInput=()=>{dirty=true;status(composing?'正在输入…':'有修改，准备保存');$('word-count').textContent=`${$('editor').value.length} 字符`;clearTimeout(timer);if(!composing)timer=setTimeout(()=>flush(),800);};
  for(const input of [$('editor'),$('doc-title')]){input.addEventListener('compositionstart',()=>{composing=true;clearTimeout(timer);});input.addEventListener('compositionend',()=>{composing=false;onInput();});input.addEventListener('input',onInput);}
  if($('live-open'))$('live-open').onclick=guard(()=>live.open());
  $('save-now').onclick=()=>flush();$('history-open').onclick=guard(historyModal);$('doc-more').onclick=guard(docMore);$('search-open').onclick=guard(()=>navigate('search'));
  renderSupport(doc);
}
async function flush(){clearTimeout(timer);if(saving)return saving;if(!dirty||!base)return true;if(composing)return false;const save=async()=>{while(dirty&&base){const id=base.id,revision=base.revision,values=editorValues(),contentChanged=values.content!==base.content;status('正在保存…');try{const saved=await repo.saveDocument(id,revision,values);base=saved;const index=state.documents.findIndex(d=>d.id===id);if(index>=0)state.documents[index]=saved;const latest=editorValues();dirty=latest.title!==values.title||latest.content!==values.content;if(!dirty){status('已保存到此浏览器');if($('editor-warning'))$('editor-warning').innerHTML='';document.querySelectorAll('[data-doc]').forEach(b=>{if(b.dataset.doc===id)b.textContent=(saved.kind==='outline'?'◇ ':'')+saved.title;});if(contentChanged)await track('edit_saved',{}, {save_state:'saved',kind:saved.kind});}}catch(err){status(err.name==='ConflictError'?'有另一份修改，需要处理':'保存失败，文字仍在编辑区',true);const warning=$('editor-warning');if(warning){warning.innerHTML=`<p>${e(err.name==='QuotaExceededError'?'浏览器存储空间不足，请先导出当前文字。不要直接清理网站数据。':err.message)}</p><button id="conflict-copy" class="secondary">保留这份内容为副本</button> <button id="draft-export" class="secondary">导出当前文字</button>`;$('draft-export').onclick=exportCurrent;$('conflict-copy').onclick=guard(async()=>{const v=editorValues();const copy=await repo.addDocument(base.workId,base.kind,v.title+' · 修改副本',v.content);dirty=false;state.docId=copy.id;await refresh();await remember();render();notify('已保留两份内容，可在列表中分别查看。');});}return false;}}return true;};saving=save();try{return await saving;}finally{saving=null;}}
async function historyModal(){if(!await flush())return;const doc=base;const items=(await repo.list('revisions')).filter(r=>r.documentId===doc.id).sort((a,b)=>b.revision-a.revision);modal('找回之前的内容',`<p class="muted small">恢复会产生新版本，当前内容也会保留。</p>${items.map(r=>`<div class="history-item"><details><summary>版本 ${r.revision} · ${new Date(r.createdAt).toLocaleString('zh-CN')} ${r.revision===doc.revision?'（当前）':''}</summary><strong>${e(r.title)}</strong><pre>${e(r.content||'（空白正文）')}</pre>${r.revision!==doc.revision?`<button data-restore="${r.id}" class="secondary">恢复这个版本</button>`:''}</details></div>`).join('')}`);document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=guard(async()=>{await repo.restoreRevision(doc.id,doc.revision,b.dataset.restore);await refresh();closeModal();render();notify('已恢复，并保留了之后的版本。');track('version_restored');}));}
async function docMore(){if(!await flush())return;modal('管理这份内容',`<div class="setting-row"><p>当前作品：${e(currentWork().title)}</p><button id="rename-work" class="secondary">重命名作品</button></div><div class="setting-row"><p>保存一份可阅读的文本</p><button id="text-export" class="secondary">导出 TXT</button></div><div class="setting-row"><p>不需要这份内容了？可在回收站找回。</p><button id="doc-delete" class="secondary danger">移到回收站</button></div>${base.kind==='chapter'?'<div class="setting-row"><p>调整章节顺序</p><div><button id="move-up" class="secondary">上移</button> <button id="move-down" class="secondary">下移</button></div></div>':''}`);$('rename-work').onclick=()=>{modal('重命名作品',`<form id="rename-form"><label for="rename-title">作品名称 <span class="field-status">必填</span></label><input id="rename-title" class="field" maxlength="80" required value="${e(currentWork().title)}"><button class="primary">保存名称</button></form>`);$('rename-form').onsubmit=guard(async ev=>{ev.preventDefault();await repo.renameWork(state.workId,$('rename-title').value);await refresh();closeModal();render();});};$('text-export').onclick=exportCurrent;$('doc-delete').onclick=guard(async()=>{await repo.saveDocument(base.id,base.revision,{deletedAt:now()},'delete');state.docId=null;await refresh();closeModal();render();notify('已移到回收站。');});if($('move-up')){const move=async direction=>{const chapters=docs().filter(d=>d.kind==='chapter'),at=chapters.findIndex(d=>d.id===base.id),target=chapters[at+direction];if(!target){notify('已经到达边界。');return;}const beyond=chapters[at+2*direction];const order=beyond?(target.order+beyond.order)/2:target.order+direction*1000;await repo.saveDocument(base.id,base.revision,{order},'reorder');await refresh();closeModal();render();};$('move-up').onclick=guard(()=>move(-1));$('move-down').onclick=guard(()=>move(1));}}
async function trashModal(){if(!await flush())return;await refresh();const deleted=state.documents.filter(d=>d.workId===state.workId&&d.deletedAt);modal('回收站',deleted.length?deleted.map(d=>`<div class="setting-row"><p>${e(d.title)}<small class="muted"> · ${KINDS[d.kind]}</small></p><button data-undelete="${d.id}" class="secondary">找回</button></div>`).join(''):'<p class="muted">这里是空的。移除的章节和资料会保留在这里。</p>');document.querySelectorAll('[data-undelete]').forEach(b=>b.onclick=guard(async()=>{const d=deleted.find(x=>x.id===b.dataset.undelete);await repo.saveDocument(d.id,d.revision,{deletedAt:null},'undelete');await refresh();closeModal();render();notify('已找回这份内容。');}));}
const setup=setupUI({repo,state,flush,refresh,remember,render,modal,closeModal,guard,notify,download,blankWorkModal,track,setFunnelContext});
if($('setup-open'))$('setup-open').onclick=guard(()=>setup.open());
const tasks=tasksUI({repo,state,docs,currentWork,refresh,navigate,modal,closeModal,guard,notify,track});
function renderTasks(){base=null;tasks.render();}
const live=liveUI({repo,state,flush,refresh,render,modal,closeModal,guard,notify});
const advanced=advancedUI({repo,state,flush,refresh,render,navigate,modal,closeModal,guard,notify,download});
$('services-open').onclick=guard(advanced.settings);
$('assistant-open').onclick=guard(advanced.assistant);
const backup=backupUI({repo,state,flush,modal,closeModal,refresh,chooseDoc,remember,render,guard,notify,track,download,trashModal,exportEncrypted:advanced.exportEncrypted});
async function backupModal(){return backup.open();}
const library=libraryUI({repo,state,docs,currentWork,flush,refresh,render,navigate,modal,closeModal,guard,notify,track,getDoc:()=>base,backupModal,download});
function renderSupport(doc){library.renderSupport(doc);}
function renderLibrary(){base=null;library.renderLibrary();}
function renderSearch(){base=null;library.renderSearch();}
async function showImport(){return library.showImport();}
$('modal-close').onclick=closeModal;$('modal').addEventListener('close',()=>modalTrigger?.focus?.());$('backup-open').onclick=guard(backupModal);
window.addEventListener('beforeunload',ev=>{if(dirty||saving){ev.preventDefault();ev.returnValue='';}});
window.addEventListener('keydown',ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='s'){ev.preventDefault();flush();}});
if(repo.channel)repo.channel.onmessage=()=>{if(dirty||saving){status('其他窗口有更新；保存时会检查版本',true);return;}status('其他窗口有更新，切换页面时会载入');};
async function unlockScreen(){status(repo.encrypted?'资料库已锁定':'为稿件设置密码');for(const id of ['setup-open','backup-open','services-open','assistant-open'])$(id).disabled=true;
  $('app').innerHTML=`<main class="welcome"><h1>${repo.encrypted?'欢迎回来，解锁你的故事':'先为你的故事设一道锁'}</h1><p>${repo.encrypted?'输入资料库密码继续写作。密码不会发给模型服务。':'稿件将在此浏览器加密保存。如有旧版资料，会一次性迁移；旧版本将无法再打开。迁移前可先导出旧版备份。'}</p>${!repo.encrypted&&repo.legacy?'<button id="legacy-export" class="secondary">迁移前导出旧版明文备份</button><p class="small">仅用于升级前保护数据。此文件未加密，请妥善保存；加密后建议换成新版备份。</p>':''}<form id="unlock-form"><label for="vault-password">资料库密码（至少 12 个字符） <span class="field-status">必填</span></label><input id="vault-password" class="field" type="password" minlength="12" maxlength="1024" autocomplete="${repo.encrypted?'current-password':'new-password'}" required>${repo.encrypted?'':'<label for="vault-confirm">再次输入密码 <span class="field-status">必填</span></label><input id="vault-confirm" class="field" type="password" minlength="12" autocomplete="new-password" required><p class="small">请保存在自己的密码管理器中。密码遗失无法找回；加密不能清除旧磁盘残留，也不能防止解锁时的恶意软件。</p>'}<button id="unlock-submit" class="primary">${repo.encrypted?'解锁':'加密并进入'}</button><p id="unlock-error" role="alert"></p></form></main>`;
  if($('legacy-export'))$('legacy-export').onclick=guard(async()=>download('升级前-明文备份.json',JSON.stringify(await repo.legacyBackup()),'application/json'));
  $('unlock-form').onsubmit=async ev=>{ev.preventDefault();const password=$('vault-password').value,button=$('unlock-submit');button.disabled=true;try{if(repo.encrypted)await repo.unlock(password);else{if(password!==$('vault-confirm').value)throw Error('两次密码不一致');await repo.initialize(password);}await start();for(const id of ['setup-open','backup-open','services-open','assistant-open'])$(id).disabled=false;}catch(err){$('unlock-error').textContent=err.message;button.disabled=false;}};
}
async function start(){await funnelReady;await refresh();const last=await repo.get('meta','last-position');if(last?.value){state.workId=state.works.some(w=>w.id===last.value.workId)?last.value.workId:state.workId;state.docId=last.value.docId;}chooseDoc();render();}
try{await repo.open();await unlockScreen();}catch(err){status('资料库无法打开',true);$('app').innerHTML=`<main class="welcome"><h1>暂时无法打开本地资料库</h1><p>${e(err.message)}</p><p>请检查浏览器是否允许本地存储。不要清除网站数据；你也可以在原浏览器导出后恢复。</p><button id="retry-open" class="primary">重新打开</button></main>`;$('retry-open').onclick=()=>location.reload();}
