import {escapeHTML as e} from './domain.mjs?v=0.4.0';
import {SCENARIOS,makeBlueprint} from './blueprint.mjs?v=0.4.0';
import {bucketLength,getVariant,startFunnelSession} from './analytics.mjs?v=0.4.1';

export function setupUI({repo,state,flush,refresh,remember,render,modal,closeModal,guard,notify,blankWorkModal,track,setFunnelContext}) {
  const $=id=>document.getElementById(id);
  let route='new',language='zh',scenario='starter',intent='',material='',materialSource='paste',materialFormat='txt',busy=false,routeChosen=false;
  let selectedScenario=null,observer=null,templateIntent=null;
  const impressions=new Set();
  const emit=(name,context={},props={})=>track(name,context,{source:'onboarding',...props});
  const scenarioProps=()=>selectedScenario?{scenario_id:selectedScenario}:{};
  async function impression(id){if(impressions.has(id))return;impressions.add(id);await emit('scenario_impression',{}, {scenario_id:id});}
  const t=(zh,en)=>language==='en'?en:zh;
  const capture=()=>{intent=$('entry-intent')?.value??intent;material=$('entry-material')?.value??material;};
  async function open(){if(!await flush())return;startFunnelSession();selectedScenario=null;templateIntent=null;impressions.clear();route='new';scenario='starter';intent='';material='';materialSource='paste';materialFormat='txt';routeChosen=false;setFunnelContext({route:'new_story',entry_mode:null});await emit('onboarding_view',{}, {source:'onboarding'});draw();}
  async function recordMigrationInput(){
    if(!material.trim())return;
    if(materialSource==='file')await emit('import_succeeded',{route:'migrate_existing',entry_mode:'file'},{import_format:materialFormat});
    else await emit('paste_saved',{route:'migrate_existing',entry_mode:'paste'},{input_length_bucket:bucketLength(material.length)});
    await emit('input_completed',{route:'migrate_existing',entry_mode:materialSource},{input_length_bucket:bucketLength(material.length)});
    await emit('material_captured',{route:'migrate_existing'},{source:'onboarding'});
  }
  function draw(){
    observer?.disconnect();
    const treatment=getVariant()==='treatment';
    const scenarioList=SCENARIOS.filter(s=>!treatment||s.id!=='migration');
    const scenarioRows=`<div class="scenario-rows">${[scenarioList.slice(0,4),scenarioList.slice(4)].filter(row=>row.length).map(row=>`<div class="scenario-row">${row.map(s=>`<button type="button" class="scenario-chip" data-scenario="${s.id}" aria-pressed="${s.id===scenario}">${e(language==='en'?s.en:s.label)}</button>`).join('')}</div>`).join('')}</div>`;
    const routes=`<div class="route-switch"><button type="button" data-route="new" class="${route==='new'?'primary':'secondary'}" aria-pressed="${route==='new'}">${treatment?'我有一个故事想法':t('我想开始新故事','Start a new story')}</button><button type="button" data-route="migrate" class="${route==='migrate'?'primary':'secondary'}" aria-pressed="${route==='migrate'}">${treatment?'我已经写了一些，但有点乱':t('我已经有一些稿件','Bring existing notes')}</button></div>`;
    const directions=treatment&&route==='new'?`<p class="small muted">${t('先用自己的话说说想法。也可以跳过，直接创建空白作品。','Start with your own words. You can skip and begin with a blank story.')}</p><label for="entry-intent">${t('一句话说想写什么','What would you like to write?')} <span class="field-status">${t('选填','Optional')}</span></label><textarea id="entry-intent" class="field area" maxlength="2000" placeholder="${t('例如：主角收到一封十年前寄来的信……；还没想好也能继续','For example: a letter arrives ten years late… You can continue without an idea.')} ">${e(intent)}</textarea><details><summary>${t('也可以从一个写作起点开始（选填）','Or start from a writing prompt (optional)')}</summary>${scenarioRows}</details>`:
      treatment?`<p class="small muted">${t('先把一段已有内容放进来；分类可以之后再做。','Bring in a passage first. You can organize it later.')}</p><label for="entry-material">${t('粘贴已有稿件','Paste existing notes')} <span class="field-status">${t('必填','Required')}</span></label><textarea id="entry-material" class="field area" required placeholder="${t('粘贴一段正文、人物设定或灵感……','Paste a passage, character note, or idea…')} ">${e(material)}</textarea><label for="entry-file">${t('或者导入 TXT / Markdown 文件','Or import a TXT / Markdown file')} <span class="field-status">${t('选填','Optional')}</span></label><input id="entry-file" class="field" type="file" accept=".txt,.md,text/plain,text/markdown"><p class="small muted">${t('单个文件最大 2 MiB；导入内容会留在本机，并先放入“待整理”。','One file up to 2 MiB. Imported text stays on this device and starts in Inbox.')}</p>`:
      `<p class="small muted">${t('创作方向（选填）：点一个获得示例，也可以直接在下面写一句话。','Direction (optional): choose a prompt or write your own sentence below.')}</p>${scenarioRows}<label for="entry-intent">${t('一句话说想写什么','What would you like to write?')} <span class="field-status">${t('选填','Optional')}</span></label><textarea id="entry-intent" class="field area" maxlength="2000" placeholder="${t('例如：主角收到一封十年前寄来的信……；还没想好也能继续','For example: a letter arrives ten years late… You can continue without an idea.')} ">${e(intent)}</textarea>${route==='migrate'?`<label for="entry-material">${t('粘贴已有稿件','Paste existing notes')} <span class="field-status">${t('选填','Optional')}</span></label><textarea id="entry-material" class="field area" placeholder="${t('现在可先留空，进入后再导入 TXT / Markdown 文件。','Leave blank and import TXT / Markdown later.')} ">${e(material)}</textarea>`:''}`;
    $('app').innerHTML=`<main class="welcome setup"><div class="setup-top"><p class="eyebrow">NOVEL WORKSPACE · 未完待续</p><label>${t('入口语言','Entry language')}<select id="entry-language"><option value="zh" ${language==='zh'?'selected':''}>中文</option><option value="en" ${language==='en'?'selected':''}>English</option></select></label></div>
      <h1>${treatment?t('先选现在最接近你的情况。','Choose the path that fits you now.'):t('让散落的想法，长成一个故事。','A home for your story and scattered notes.')}</h1><p>${treatment?t('不用先起标题或整理分类，后面都可以修改。','No title or category setup is needed. You can change them later.'):t('把大纲、人物和资料放在一起。先整理一个能继续写下去的空间。','Keep your outline, characters and references together, ready to write.')}</p>
      ${routes}<form id="setup-form" class="setup-form">${directions}<p class="small muted">${t('使用本地模板准备结构，保留你的原话。没有调用 AI，稿件不会上传。','Local templates preserve your words. No AI call or manuscript upload. The writing workspace uses Chinese navigation.')}</p><div class="actions"><button class="primary">${treatment&&route==='new'?'创建并开始写作':treatment?'整理这份内容':'预览我的写作空间'}</button>${route==='new'?`<button id="skip-setup" type="button" class="quiet">${t('创建空白作品','Create a blank story')}</button>`:''}</div><p id="entry-error" class="danger" role="alert"></p></form>
      ${state.workId?`<button id="return-work" class="quiet">${t('回到我的作品','Back to my story')}</button>`:''}</main>`;
    document.querySelectorAll('[data-route]').forEach(b=>b.onclick=async()=>{capture();route=b.dataset.route;selectedScenario=null;routeChosen=true;const routeName=route==='migrate'?'migrate_existing':'new_story';setFunnelContext({route:routeName,entry_mode:null});draw();await emit('route_selected',{route:routeName},{source:'onboarding'});});
    $('entry-language').onchange=ev=>{capture();language=ev.target.value;draw();};
    document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=async()=>{capture();const old=SCENARIOS.find(x=>x.id===scenario),oldExample=language==='en'?`I want a writing space for ${old.en.toLowerCase()}, with an outline and a first chapter.`:old.example;const replaceExample=!intent.trim()||intent===oldExample;scenario=b.dataset.scenario;selectedScenario=scenario;const pickedScenario=scenario;const s=SCENARIOS.find(x=>x.id===scenario);if(replaceExample){intent=language==='en'?`I want a writing space for ${s.en.toLowerCase()}, with an outline and a first chapter.`:s.example;templateIntent=intent;}if(scenario==='migration'&&!treatment){route='migrate';routeChosen=true;await emit('route_selected',{route:'migrate_existing'},{source:'onboarding'});}const routeName=route==='migrate'?'migrate_existing':'new_story';setFunnelContext({route:routeName,entry_mode:'template'});draw();$('entry-intent')?.focus();await impression(pickedScenario);await emit('scenario_selected',{route:routeName,entry_mode:'template'},{scenario_id:pickedScenario});await emit('entry_mode_selected',{route:routeName,entry_mode:'template'});});
    if(typeof IntersectionObserver!=='undefined'){observer=new IntersectionObserver(entries=>{for(const item of entries)if(item.isIntersecting&&item.intersectionRatio>=0.5&&document.visibilityState==='visible'){void impression(item.target.dataset.scenario);}}, {threshold:0.5});document.querySelectorAll('[data-scenario]').forEach(card=>observer.observe(card));}
    if($('skip-setup'))$('skip-setup').onclick=guard(async()=>{const routeName=route==='migrate'?'migrate_existing':'new_story';if(!routeChosen){await emit('route_selected',{route:routeName});routeChosen=true;}setFunnelContext({route:routeName,entry_mode:'blank'});await emit('entry_mode_selected',{route:routeName,entry_mode:'blank'});await emit('input_completed',{route:routeName,entry_mode:'blank'},{input_length_bucket:'0',...scenarioProps()});await blankWorkModal();});
    if($('return-work'))$('return-work').onclick=render;
    if($('entry-file'))$('entry-file').onchange=async ev=>{const file=ev.target.files?.[0];if(!file)return;try{const format=file.name.toLowerCase().endsWith('.md')?'md':file.name.toLowerCase().endsWith('.txt')?'txt':null;if(!format)throw Error('请选择 TXT 或 Markdown 文件。');if(file.size>2*1024*1024)throw Error('单个文件最大 2 MiB。');await emit('import_started',{route:'migrate_existing',entry_mode:'file'},{import_format:format});const bytes=await file.arrayBuffer();material=new TextDecoder('utf-8',{fatal:true}).decode(bytes);materialSource='file';materialFormat=format;$('entry-material').value=material;}catch(err){material='';materialSource='paste';$('entry-material').value='';$('entry-error').textContent=err.message||'文件无法读取。';}};
    $('setup-form').onsubmit=async ev=>{ev.preventDefault();if(busy)return;capture();try{const routeName=route==='migrate'?'migrate_existing':'new_story';if(!routeChosen){await emit('route_selected',{route:routeName},{source:'onboarding'});routeChosen=true;}const mode=route==='migrate'?(material.trim()?materialSource:'blank'):(intent.trim()?(intent===templateIntent?'template':'natural_language'):'blank');if(treatment&&route==='migrate'&&!material.trim())throw Error('请粘贴一段已有内容，或选择 TXT / Markdown 文件。');setFunnelContext({route:routeName,entry_mode:mode});await emit('entry_mode_selected',{route:routeName,entry_mode:mode});if(route==='new'&&intent.trim()&&mode!=='blank'){await emit('intent_submitted',{route:routeName,entry_mode:mode},{input_length_bucket:bucketLength(intent.length),...scenarioProps()});await emit('input_completed',{route:routeName,entry_mode:mode},{input_length_bucket:bucketLength(intent.length),...scenarioProps()});}else if(route==='new'){await emit('input_completed',{route:routeName,entry_mode:mode},{input_length_bucket:'0',...scenarioProps()});}const plan=makeBlueprint({intent,route,scenario,language,material,entryMode:mode});if(treatment){const result=await repo.createFromBlueprint(plan);observer?.disconnect();state.workId=result.work.id;state.docId=result.chapter.id;state.page=route==='migrate'?'search':'write';await refresh();await remember();render();await emit('workspace_created',{route:routeName});await emit('first_artifact_ready',{route:routeName});if(route==='migrate')await recordMigrationInput();if(plan.hasCapturedIntent)await emit('material_captured',{route:routeName},{source:'onboarding'});notify(route==='migrate'?'内容已保存在本机。搜索一句原文，确认它能找回来。':'作品已创建，可以直接写第一段。');}else preview(plan);}catch(err){$('entry-error').textContent=err.message;}};
  }
  function preview(plan){
    modal(t('准备开始你的故事','Ready to start your story'),`<p class="badge">${t('本地模板 · 尚未创建','Local template · not created yet')}</p><label for="delivery-title">${t('作品名称','Story title')} <span class="field-status">${t('选填','Optional')}</span></label><input id="delivery-title" class="field" maxlength="80" value="${e(plan.title)}"><p class="small muted">${t('留空会使用预览中的名称，以后也能改。','Leave blank to keep the suggested title; you can rename it later.')}</p><ul>${plan.documents.map(d=>`<li>${e(d.title)}</li>`).join('')}</ul><details><summary>${t('查看大纲','Preview outline')}</summary><pre class="preview-text">${e(plan.documents[0].content)}</pre></details><p>${t('还会准备两项创作任务。创建后可继续编辑。','Two writing tasks are included. Everything remains editable.')}</p><button id="deliver-now" class="primary full">${t('创建并开始写作','Create and start writing')}</button>`);
    $('deliver-now').onclick=async ev=>{
      if(busy)return;busy=true;const button=ev.currentTarget,close=$('modal-close');button.disabled=true;close.disabled=true;const cancel=e=>e.preventDefault();$('modal').addEventListener('cancel',cancel);
      try{plan.title=$('delivery-title').value.trim()||plan.title;const result=await repo.createFromBlueprint(plan);observer?.disconnect();state.workId=result.work.id;state.docId=result.chapter.id;state.page=route==='migrate'?'library':'write';await refresh();await remember();closeModal();render();const routeName=route==='migrate'?'migrate_existing':'new_story';await emit('workspace_created',{route:routeName});await emit('first_artifact_ready',{route:routeName});if(route==='migrate')await recordMigrationInput();if(plan.hasCapturedIntent)await emit('material_captured',{route:routeName},{source:'onboarding'});notify(t('空间已保存。可以开始写作，也可以先找回资料。','Your workspace is saved. Start writing or find a note.'));}
      catch(err){$('modal-error').textContent=err.message;button.disabled=false;}
      finally{busy=false;close.disabled=false;$('modal').removeEventListener('cancel',cancel);}
    };
  }
  return {open};
}
